media:
  - name: images
    label: Images
    input: public/images
    output: /images
    path: /
    categories: [image]
  - name: specs
    label: Specs (PDFs & CSVs)
    input: public/specs
    output: /specs
    path: /
    categories: [document]

content:
  - name: products
    label: Products
    type: collection
    path: content/products
    format: json
    filename: "{slug}.json"
    fields:
      - name: id
        label: ID
        type: string
        required: true
      - name: slug
        label: Slug
        type: string
        required: true
      - name: categoryId
        label: Category ID
        type: number
        required: true
      - name: name
        label: Name (English)
        type: string
      - name: nameFa
        label: Name (Persian)
        type: string
        required: true
      - name: description
        label: Description (English)
        type: text
      - name: descriptionFa
        label: Description (Persian)
        type: text
      - name: image
        label: Main Image
        type: image
      - name: pdfFile
        label: PDF File
        type: string
        description: Filename in public/specs/ (e.g. ljb-1s.pdf)
      - name: specCsvFile
        label: Spec CSV File
        type: string
        description: Filename in public/specs/ (e.g. ljb-1s.csv)
      - name: inStock
        label: In Stock
        type: boolean
    view:
      fields: [nameFa, slug, categoryId, inStock]
      primary: nameFa
      sort: [nameFa, slug]
      default:
        sort: nameFa
        order: asc

  - name: product-categories
    label: Product Categories
    type: collection
    path: content/product-categories
    format: json
    filename: "{id}.json"
    fields:
      - name: id
        label: ID
        type: number
        required: true
      - name: title
        label: Title (English)
        type: string
        required: true
      - name: titleFa
        label: Title (Persian)
        type: string
        required: true
      - name: image
        label: Image
        type: image
    view:
      fields: [titleFa, id, title]
      primary: titleFa
      sort: [id, titleFa]
      default:
        sort: id
        order: asc
